/**
 * Mock LLM-style "agent" execution.
 *
 * Replace `runAgent()` with your real LLM call, tool use, retrieval pipeline,
 * etc. The function is intentionally async to match how a real agent would
 * look. It also returns a `tokensUsed` so you could imagine charging on
 * completion if you preferred a meter-then-bill flow (this template charges
 * up-front, which is the simpler model).
 */
import type { PaymentIntent } from './intent.js'

export type AgentResult = {
  output: string
  model: string
  tokensUsed: number
  finishedAt: string
}

export async function runAgent(intent: PaymentIntent): Promise<AgentResult> {
  // Simulate a small amount of work so timings look realistic.
  await new Promise((r) => setTimeout(r, 50))

  const output = generateMockOutput(intent.prompt, intent.maxTokens)
  return {
    output,
    model: intent.model,
    tokensUsed: Math.min(intent.maxTokens, output.split(/\s+/).length),
    finishedAt: new Date().toISOString(),
  }
}

function generateMockOutput(prompt: string, maxTokens: number): string {
  const summary = prompt.length > 80 ? `${prompt.slice(0, 80)}...` : prompt
  const filler = [
    'This is a deterministic mock response from the XRPL MPP agent template.',
    `It would normally be generated by an LLM up to ${maxTokens} tokens.`,
    `You sent: "${summary}".`,
    'Replace runAgent() in src/agent.ts with your real model call.',
  ]
  const wordsAvailable = filler.join(' ').split(/\s+/)
  return wordsAvailable.slice(0, maxTokens).join(' ')
}
